name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin

      - name: Create Droplet
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          SSH_KEY_ID: ${{ secrets.SSH_KEY_ID }}
          RESERVED_IP: ${{ secrets.RESERVED_IP }}
        run: |
          chmod +x create_droplet.sh
          ./create_droplet.sh

  build:
    runs-on: ubuntu-latest
    needs: create-droplet
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-app .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Docker image
        run: docker run my-app ./run-tests.sh

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Droplet
        env:
          RESERVED_IP: ${{ secrets.RESERVED_IP }}
        run: ssh root@$RESERVED_IP 'docker pull my-app && docker run -d my-app'